CREATE TABLE FEE (
  FEE_ID int(10) NOT NULL AUTO_INCREMENT,
  STUDENT_ID int(10) DEFAULT NULL, 
  AMOUNT int(10) DEFAULT NULL, 
  MONTH varchar(15) DEFAULT NULL,
  PORT int(10) DEFAULT NULL,
  PRIMARY KEY (FEE_ID)
);

insert into FEE(STUDENT_ID,AMOUNT,MONTH,PORT)
values(25,1000,'JUNE',0);
insert into FEE(STUDENT_ID,AMOUNT,MONTH,PORT)
values(27,2000,'May',0);
insert into FEE(STUDENT_ID,AMOUNT,MONTH,PORT)
values(28,3000,'April',0);

insert into FEE(FEE_ID,STUDENT_ID,AMOUNT,MONTH,PORT)
values(5,1,1000,'JUNE',0);
insert into FEE(FEE_ID,STUDENT_ID,AMOUNT,MONTH,PORT)
values(6,2,2000,'May',0);